# Generated by Django 2.0.6 on 2019-01-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('file_type', models.IntegerField(choices=[(0, '员工岗前培训'), (1, '技能培训'), (2, '重点区域安全卡控'), (3, '风险源识别')], default=0, verbose_name='文件类型')),
                ('file_s', models.FileField(upload_to='Safety_file', verbose_name='文件')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
