# Generated by Django 2.1.3 on 2019-01-24 08:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyfile',
            name='file_s',
            field=models.FileField(blank=True, null=True, upload_to='safety/%Y/%m/%d/', validators=[core.utils.validate_file_extension], verbose_name='文件'),
        ),
    ]
