# Generated by Django 2.1.7 on 2019-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='设置类别')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='设置类别显示')),
                ('img', models.ImageField(default='none', upload_to='settings')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
