# Generated by Django 2.1.3 on 2018-11-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=120)),
                ('dept_boss', models.CharField(max_length=30)),
                ('dept_position', models.CharField(max_length=10)),
                ('boos_phone', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': '部门',
            },
        ),
    ]
