# Generated by Django 2.1.3 on 2019-01-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_avatar',
            field=models.ImageField(blank=True, default='none', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
