# Generated by Django 2.1.3 on 2018-11-10 06:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='AssignAccount',
        ),
        migrations.AlterModelOptions(
            name='assignaccount',
            options={'verbose_name': 'AssignAccount', 'verbose_name_plural': 'AssignAccounts'},
        ),
    ]
