# Generated by Django 2.1.3 on 2019-01-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190115_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(blank=True, to='member.Role', verbose_name='拥有角色'),
        ),
    ]
