# Generated by Django 2.1.3 on 2018-11-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Departments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departments',
            name='boos_phone',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dept_boss',
            field=models.CharField(max_length=30, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(max_length=120, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dept_position',
            field=models.CharField(max_length=10, verbose_name='职务'),
        ),
    ]
