# Generated by Django 2.1.3 on 2018-11-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20181110_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11, unique=True, verbose_name='员工工号')),
                ('member_avatar', models.ImageField(default='none', upload_to='avatar', verbose_name='头像')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(max_length=5, verbose_name='性别')),
                ('birthday', models.CharField(max_length=50, verbose_name='出生年月')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('phone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Departments', verbose_name='部门')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
