# Generated by Django 2.1.3 on 2019-01-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190116_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enp',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='密码'),
        ),
    ]
