# Generated by Django 2.1.5 on 2019-01-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20190111_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Departments', verbose_name='部门'),
        ),
    ]
