# Generated by Django 2.1.3 on 2019-01-09 06:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0004_auto_20181114_1956'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assignaccount',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='assignaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='assignaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='assignaccount',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
