# Generated by Django 2.1.3 on 2019-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190111_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(max_length=120, unique=True, verbose_name='部门名称'),
        ),
    ]
