# Generated by Django 2.1.5 on 2019-01-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190111_2239'),
        ('member', '0004_auto_20190116_1717'),
    ]

    operations = [
    ]
