# Generated by Django 2.1.7 on 2019-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_merge_20190117_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(default=' ', max_length=20, verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='姓名'),
        ),
    ]
