# Generated by Django 2.1.3 on 2019-01-09 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0005_auto_20190109_1430'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assignaccount',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='assignaccount',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='assignaccount',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignaccount',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
