# Generated by Django 2.1.3 on 2019-01-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20190109_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['id'], 'verbose_name': '部门'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_id'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(default=' ', max_length=50, verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='member',
            name='blood_type',
            field=models.CharField(default='未知', max_length=10, verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nation',
            field=models.CharField(default='汉', max_length=10, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default=' ', max_length=11, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(default=' ', max_length=50, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(default=' ', max_length=5, verbose_name='性别'),
        ),
    ]
