# Generated by Django 2.1.5 on 2019-01-10 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20190110_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
