# Generated by Django 2.1.5 on 2019-01-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20190110_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限名称')),
                ('url', models.CharField(max_length=255, verbose_name='含正则的URL')),
                ('code', models.CharField(max_length=32, verbose_name='权限代码')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(to='member.Permission', verbose_name='拥有权限')),
            ],
        ),
        migrations.AddField(
            model_name='assignaccount',
            name='roles',
            field=models.ManyToManyField(to='member.Role', verbose_name='拥有角色'),
        ),
    ]
