# Generated by Django 2.1.7 on 2019-02-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Profess',
                'verbose_name_plural': 'Professs',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='acceptor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='验收人'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=155, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='status_id',
            field=models.IntegerField(choices=[(0, '安装'), (1, '调试')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='device',
            name='profess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profess', to='device.Profess', verbose_name='专业'),
        ),
    ]
