# Generated by Django 2.1.7 on 2019-02-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20190227_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z1', models.CharField(blank=True, max_length=50, null=True, verbose_name='实验方式')),
                ('z2', models.CharField(blank=True, max_length=50, null=True, verbose_name='取样地点')),
                ('z3', models.DateTimeField(blank=True, null=True, verbose_name='取样时间')),
                ('z4', models.CharField(blank=True, max_length=50, null=True, verbose_name='取样人')),
                ('z5', models.CharField(blank=True, max_length=50, null=True, verbose_name='检验项目')),
                ('z6', models.CharField(blank=True, max_length=50, null=True, verbose_name='检验日期')),
                ('z7', models.CharField(blank=True, max_length=50, null=True, verbose_name='执行标准')),
                ('z8', models.CharField(blank=True, max_length=50, null=True, verbose_name='保养内容')),
                ('z9', models.CharField(blank=True, max_length=50, null=True, verbose_name='注意事项')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z1', models.CharField(blank=True, max_length=50, null=True, verbose_name='站点')),
                ('z2', models.CharField(blank=True, max_length=50, null=True, verbose_name='安装位置')),
                ('z3', models.CharField(blank=True, max_length=50, null=True, verbose_name='主要部件生产厂家')),
                ('z4', models.CharField(blank=True, max_length=50, null=True, verbose_name='材料名称')),
                ('z5', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格型号')),
                ('z6', models.DateTimeField(blank=True, null=True, verbose_name='进场时间')),
                ('z7', models.CharField(blank=True, max_length=50, null=True, verbose_name='生产厂家')),
                ('z8', models.CharField(blank=True, max_length=50, null=True, verbose_name='合格证号')),
                ('z9', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用部位')),
                ('z10', models.CharField(blank=True, max_length=50, null=True, verbose_name='现场验收结论')),
            ],
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['id'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AddField(
            model_name='devicetestinfo',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='device.Device'),
        ),
        migrations.AddField(
            model_name='devicebaseinfo',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='device.Device'),
        ),
    ]
