# Generated by Django 2.1.5 on 2019-02-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20190227_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicebaseinfo',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='z1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='实验方式'),
        ),
        migrations.AddField(
            model_name='device',
            name='z2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='取样地点'),
        ),
        migrations.AddField(
            model_name='device',
            name='z3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取样时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='z4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='取样人'),
        ),
        migrations.AddField(
            model_name='device',
            name='z5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='检验项目'),
        ),
        migrations.AddField(
            model_name='device',
            name='z6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='检验日期'),
        ),
        migrations.AddField(
            model_name='device',
            name='z7',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='执行标准'),
        ),
        migrations.AddField(
            model_name='device',
            name='z8',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='保养内容'),
        ),
        migrations.AddField(
            model_name='device',
            name='z9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注意事项'),
        ),
        migrations.DeleteModel(
            name='DeviceBaseInfo',
        ),
    ]
