# Generated by Django 2.1.5 on 2019-02-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20190227_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='z1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='安装位置'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主要部件生产厂家'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='材料名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z6',
            field=models.DateTimeField(blank=True, null=True, verbose_name='进场时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z7',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='生产厂家'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z8',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='合格证号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='z9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='使用部位'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='device.Device'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='实验方式'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='取样地点'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取样时间'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='取样人'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='检验项目'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='检验日期'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z7',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='执行标准'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z8',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='保养内容'),
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='z9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注意事项'),
        ),
    ]
