# Generated by Django 2.1.3 on 2019-02-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20190227_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetestinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='devicetestinfo',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='test', serialize=False, to='device.Device'),
        ),
    ]
