# Generated by Django 2.1.7 on 2019-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20190306_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetestinfo',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='acceptor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='验收人'),
        ),
        migrations.AddField(
            model_name='device',
            name='t1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='实验方式'),
        ),
        migrations.AddField(
            model_name='device',
            name='t10',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='现场验收结论'),
        ),
        migrations.AddField(
            model_name='device',
            name='t2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='取样地点'),
        ),
        migrations.AddField(
            model_name='device',
            name='t3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取样时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='t4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='取样人'),
        ),
        migrations.AddField(
            model_name='device',
            name='t5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='检验项目'),
        ),
        migrations.AddField(
            model_name='device',
            name='t6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='检验日期'),
        ),
        migrations.AddField(
            model_name='device',
            name='t7',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='执行标准'),
        ),
        migrations.AddField(
            model_name='device',
            name='t8',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='保养内容'),
        ),
        migrations.AddField(
            model_name='device',
            name='t9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='注意事项'),
        ),
        migrations.DeleteModel(
            name='DeviceTestInfo',
        ),
    ]
