# Generated by Django 2.1.5 on 2019-03-11 05:20

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20190306_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='file_s',
            field=models.FileField(blank=True, null=True, upload_to='device/%Y/%m/%d/', validators=[core.utils.validate_file_extension], verbose_name='文件'),
        ),
    ]
