# Generated by Django 2.1.7 on 2019-02-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Profess',
                'verbose_name_plural': 'Professs',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('job_name', models.CharField(max_length=50, verbose_name='作业名称')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('location', models.CharField(max_length=30, verbose_name='施工地点')),
                ('done_count', models.IntegerField(default=0, verbose_name='开累完成量')),
                ('design_total', models.IntegerField(default=0, verbose_name='设计总量')),
                ('last_week_plan', models.IntegerField(default=0, verbose_name='上周计划完成量')),
                ('last_week_actual', models.IntegerField(default=0, verbose_name='上周实际完成量')),
                ('now_week_plan', models.IntegerField(default=0, verbose_name='本周计划完成量')),
                ('now_week_actual', models.IntegerField(default=0, verbose_name='本周实际完成量')),
                ('now_week', models.IntegerField(default=1, verbose_name='当前周目')),
                ('profess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profess', to='schedule.Profess', verbose_name='专业')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
