# Generated by Django 2.1.7 on 2019-03-02 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190227_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['id'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
