# Generated by Django 2.1.5 on 2019-03-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190306_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='job_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='作业名称'),
        ),
    ]
