# Generated by Django 2.1.5 on 2019-03-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190311_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='job_name',
            field=models.CharField(max_length=20, verbose_name='作业名称'),
        ),
    ]
