# Generated by Django 2.1.5 on 2019-02-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Profess',
                'verbose_name_plural': 'Professs',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='manufacturer',
            field=models.CharField(default='无', max_length=30, verbose_name='生产厂家'),
        ),
        migrations.AddField(
            model_name='material',
            name='profess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profess', to='material.Profess', verbose_name='专业'),
        ),
    ]
