# Generated by Django 2.1.7 on 2019-02-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190221_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
    ]
