# Generated by Django 2.1.7 on 2019-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20190226_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=155, verbose_name='物资名称'),
        ),
    ]
