# Generated by Django 2.1.7 on 2019-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20190301_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='manufacturer',
            field=models.CharField(default='无', max_length=20, verbose_name='生产厂家'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=20, verbose_name='物资名称'),
        ),
        migrations.AlterField(
            model_name='profess',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
