# Generated by Django 2.0.6 on 2019-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('profess', models.IntegerField(choices=[(0, '电力变电'), (1, '接触网'), (2, '通信'), (3, '信号')], default=0, verbose_name='专业')),
                ('file_type', models.IntegerField(choices=[(0, '图纸会审情况'), (1, '技术交底'), (2, '作业指导书'), (3, '工艺工法')], default=0, verbose_name='文件类型')),
                ('file_s', models.FileField(upload_to='technology_file', verbose_name='文件')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
