# Generated by Django 2.1.3 on 2019-01-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyfile',
            name='file_s',
            field=models.FileField(upload_to='technology/%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
