# Generated by Django 2.1.3 on 2019-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_auto_20190124_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyfile',
            name='file_s',
            field=models.FileField(blank=True, null=True, upload_to='technology/%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
