# Generated by Django 2.1.3 on 2019-01-24 08:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0003_auto_20190124_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyfile',
            name='file_s',
            field=models.FileField(blank=True, null=True, upload_to='technology/%Y/%m/%d/', validators=[core.utils.validate_file_extension], verbose_name='文件'),
        ),
    ]
