# Generated by Django 2.1.5 on 2019-02-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0004_auto_20190124_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Profess',
                'verbose_name_plural': 'Professs',
            },
        ),
        migrations.AlterField(
            model_name='technologyfile',
            name='profess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profess', to='technology.Profess', verbose_name='专业'),
        ),
    ]
