# Generated by Django 2.1.7 on 2019-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_auto_20190216_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profess',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='technologyfile',
            name='title',
            field=models.CharField(max_length=20, verbose_name='标题'),
        ),
    ]
